### ISSUE TITLE
Function Work

### ISSUE THREAD

**Issue by Kimsumi111** [Kimsumi111/ClickApple#1]
---
name: Complete this Game
about: complete this small game
title: ''ClickApple"
labels: enhancement
assignees: Kimsumi111

---

## Description
What to do.

## Tasks
- [x] 입력 시스템 구현
- [x] 노트 그룹 리소스 활용
- [x] 노트 생성 및 배치
- [x] 노트 그룹 애니메이션 및 조작
- [x] 랜덤 인스턴스 생성
- [x] UI 구현
- [x] 가변화 구현
- [x] 동적 생성 구현
- [x] 게임 종료 부분 구현
- [x] 폴리싱 및 마무리
