### ISSUE TITLE
Small Project one

### ISSUE THREAD

**Issue by Kimsumi111** [Kimsumi111/ClickApple#1]
---
name: Function Work
about: Base work
title: ''Click Apple"
labels: enhancement
assignees: Kimsumi111

---

## Description
Generate input system, notes, UI, variability.

## Tasks
- [ ] 입력 시스템 구현
- [ ] 노트 그룹 리소스
- [ ] 노트 생성 및 배치
- [ ] 노트 애니메이션
- [ ] 랜덤 인스턴스 생성
- [ ] UI
- [ ] 가변화 구현
- [ ] 노트 동적 생성 구현
- [ ] 종료 부분 구현 및 폴리싱
